# Generated by Django 2.1.7 on 2019-04-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='group_client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crm.GroupClient'),
            preserve_default=False,
        ),
    ]
